server:
  port: 8000
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
        - name: LoggingFilter
          args:
            baseMessage: Hi, there.
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
