apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: jaesuk95/config-server:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
spec:
  type: NodePort
  selector:
    app: config-service
  ports:
  - port: 80
    targetPort: 8888
