server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/jaesuk/IdeaProjects/msa/git-local-repo
          uri: https://github.com/jaesuk95/inflearn-spring-cloud-config.git
#          private 일 경우
#          username: [username]
#          password: [password]
